#DropDB NpoMash.Erm.Hrm.Test
#Application NpoMash.Erm.Hrm.Tests.Win

*Action TesterWC_PopulateAction
*Action Обновить
*Action Создать
*Action Alloc Parameters
*Action Alloc Parameters.Сформировать параметры расчета
*Action Сохранить
*Action Закрыть
*Action Закрыть
*HandleDialog
 Respond = Yes
*Action Создать
*Action Alloc Parameters
*Action Alloc Parameters.Сформировать параметры расчета
*Action Закрыть
*Action Закрыть
*HandleDialog
 Respond = Yes
*Action Закрыть
*Action Закрыть
*HandleDialog
 Respond = No
*Action Создать
*Action Alloc Parameters
*Action Alloc Parameters.Сформировать параметры расчета
*Action Закрыть
*HandleDialog
 Respond = No