#DropDB NpoMash.Erm.Hrm.Test
#Application NpoMash.Erm.Hrm.Tests.Win

*Action TesterWC_PopulateAction
*Action Обновить
*Action Создать
*Action Alloc Parameters
*Action Alloc Parameters.Сформировать параметры расчета
*Action Контроль заказа
*Action Контроль заказа.Создать
*FillForm
 Заказ = IntecoAG.Erm.FM.Order.fmCOrder(01ecc80c-646f-412d-a8c6-cb6e7b6a5668)
*Action Сохранить
*Action Закрыть